language: node_js
node_js:
- '5.10.1'
addons:
  apt:
    packages:
      - sshpass
before_script:
  - npm install
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: tools/deploy.sh
  on:
    branch: master